<?php

/**
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Taskrouter
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
namespace ShopMagicTwilioVendor\Twilio\Rest\Taskrouter\V1;

use ShopMagicTwilioVendor\Twilio\Exceptions\TwilioException;
use ShopMagicTwilioVendor\Twilio\InstanceResource;
use ShopMagicTwilioVendor\Twilio\Options;
use ShopMagicTwilioVendor\Twilio\Values;
use ShopMagicTwilioVendor\Twilio\Version;
use ShopMagicTwilioVendor\Twilio\Deserialize;
use ShopMagicTwilioVendor\Twilio\Rest\Taskrouter\V1\Workspace\TaskQueueList;
use ShopMagicTwilioVendor\Twilio\Rest\Taskrouter\V1\Workspace\EventList;
use ShopMagicTwilioVendor\Twilio\Rest\Taskrouter\V1\Workspace\TaskChannelList;
use ShopMagicTwilioVendor\Twilio\Rest\Taskrouter\V1\Workspace\ActivityList;
use ShopMagicTwilioVendor\Twilio\Rest\Taskrouter\V1\Workspace\WorkerList;
use ShopMagicTwilioVendor\Twilio\Rest\Taskrouter\V1\Workspace\WorkflowList;
use ShopMagicTwilioVendor\Twilio\Rest\Taskrouter\V1\Workspace\TaskList;
use ShopMagicTwilioVendor\Twilio\Rest\Taskrouter\V1\Workspace\WorkspaceCumulativeStatisticsList;
use ShopMagicTwilioVendor\Twilio\Rest\Taskrouter\V1\Workspace\WorkspaceRealTimeStatisticsList;
use ShopMagicTwilioVendor\Twilio\Rest\Taskrouter\V1\Workspace\WorkspaceStatisticsList;
/**
 * @property string|null $accountSid
 * @property \DateTime|null $dateCreated
 * @property \DateTime|null $dateUpdated
 * @property string|null $defaultActivityName
 * @property string|null $defaultActivitySid
 * @property string|null $eventCallbackUrl
 * @property string|null $eventsFilter
 * @property string|null $friendlyName
 * @property bool|null $multiTaskEnabled
 * @property string|null $sid
 * @property string|null $timeoutActivityName
 * @property string|null $timeoutActivitySid
 * @property string $prioritizeQueueOrder
 * @property string|null $url
 * @property array|null $links
 */
class WorkspaceInstance extends \ShopMagicTwilioVendor\Twilio\InstanceResource
{
    protected $_taskQueues;
    protected $_events;
    protected $_taskChannels;
    protected $_activities;
    protected $_workers;
    protected $_workflows;
    protected $_tasks;
    protected $_cumulativeStatistics;
    protected $_realTimeStatistics;
    protected $_statistics;
    /**
     * Initialize the WorkspaceInstance
     *
     * @param Version $version Version that contains the resource
     * @param mixed[] $payload The response payload
     * @param string $sid The SID of the Workspace resource to delete.
     */
    public function __construct(\ShopMagicTwilioVendor\Twilio\Version $version, array $payload, string $sid = null)
    {
        parent::__construct($version);
        // Marshaled Properties
        $this->properties = ['accountSid' => \ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'account_sid'), 'dateCreated' => \ShopMagicTwilioVendor\Twilio\Deserialize::dateTime(\ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'date_created')), 'dateUpdated' => \ShopMagicTwilioVendor\Twilio\Deserialize::dateTime(\ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'date_updated')), 'defaultActivityName' => \ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'default_activity_name'), 'defaultActivitySid' => \ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'default_activity_sid'), 'eventCallbackUrl' => \ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'event_callback_url'), 'eventsFilter' => \ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'events_filter'), 'friendlyName' => \ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'friendly_name'), 'multiTaskEnabled' => \ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'multi_task_enabled'), 'sid' => \ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'sid'), 'timeoutActivityName' => \ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'timeout_activity_name'), 'timeoutActivitySid' => \ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'timeout_activity_sid'), 'prioritizeQueueOrder' => \ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'prioritize_queue_order'), 'url' => \ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'url'), 'links' => \ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'links')];
        $this->solution = ['sid' => $sid ?: $this->properties['sid']];
    }
    /**
     * Generate an instance context for the instance, the context is capable of
     * performing various actions.  All instance actions are proxied to the context
     *
     * @return WorkspaceContext Context for this WorkspaceInstance
     */
    protected function proxy() : \ShopMagicTwilioVendor\Twilio\Rest\Taskrouter\V1\WorkspaceContext
    {
        if (!$this->context) {
            $this->context = new \ShopMagicTwilioVendor\Twilio\Rest\Taskrouter\V1\WorkspaceContext($this->version, $this->solution['sid']);
        }
        return $this->context;
    }
    /**
     * Delete the WorkspaceInstance
     *
     * @return bool True if delete succeeds, false otherwise
     * @throws TwilioException When an HTTP error occurs.
     */
    public function delete() : bool
    {
        return $this->proxy()->delete();
    }
    /**
     * Fetch the WorkspaceInstance
     *
     * @return WorkspaceInstance Fetched WorkspaceInstance
     * @throws TwilioException When an HTTP error occurs.
     */
    public function fetch() : \ShopMagicTwilioVendor\Twilio\Rest\Taskrouter\V1\WorkspaceInstance
    {
        return $this->proxy()->fetch();
    }
    /**
     * Update the WorkspaceInstance
     *
     * @param array|Options $options Optional Arguments
     * @return WorkspaceInstance Updated WorkspaceInstance
     * @throws TwilioException When an HTTP error occurs.
     */
    public function update(array $options = []) : \ShopMagicTwilioVendor\Twilio\Rest\Taskrouter\V1\WorkspaceInstance
    {
        return $this->proxy()->update($options);
    }
    /**
     * Access the taskQueues
     */
    protected function getTaskQueues() : \ShopMagicTwilioVendor\Twilio\Rest\Taskrouter\V1\Workspace\TaskQueueList
    {
        return $this->proxy()->taskQueues;
    }
    /**
     * Access the events
     */
    protected function getEvents() : \ShopMagicTwilioVendor\Twilio\Rest\Taskrouter\V1\Workspace\EventList
    {
        return $this->proxy()->events;
    }
    /**
     * Access the taskChannels
     */
    protected function getTaskChannels() : \ShopMagicTwilioVendor\Twilio\Rest\Taskrouter\V1\Workspace\TaskChannelList
    {
        return $this->proxy()->taskChannels;
    }
    /**
     * Access the activities
     */
    protected function getActivities() : \ShopMagicTwilioVendor\Twilio\Rest\Taskrouter\V1\Workspace\ActivityList
    {
        return $this->proxy()->activities;
    }
    /**
     * Access the workers
     */
    protected function getWorkers() : \ShopMagicTwilioVendor\Twilio\Rest\Taskrouter\V1\Workspace\WorkerList
    {
        return $this->proxy()->workers;
    }
    /**
     * Access the workflows
     */
    protected function getWorkflows() : \ShopMagicTwilioVendor\Twilio\Rest\Taskrouter\V1\Workspace\WorkflowList
    {
        return $this->proxy()->workflows;
    }
    /**
     * Access the tasks
     */
    protected function getTasks() : \ShopMagicTwilioVendor\Twilio\Rest\Taskrouter\V1\Workspace\TaskList
    {
        return $this->proxy()->tasks;
    }
    /**
     * Access the cumulativeStatistics
     */
    protected function getCumulativeStatistics() : \ShopMagicTwilioVendor\Twilio\Rest\Taskrouter\V1\Workspace\WorkspaceCumulativeStatisticsList
    {
        return $this->proxy()->cumulativeStatistics;
    }
    /**
     * Access the realTimeStatistics
     */
    protected function getRealTimeStatistics() : \ShopMagicTwilioVendor\Twilio\Rest\Taskrouter\V1\Workspace\WorkspaceRealTimeStatisticsList
    {
        return $this->proxy()->realTimeStatistics;
    }
    /**
     * Access the statistics
     */
    protected function getStatistics() : \ShopMagicTwilioVendor\Twilio\Rest\Taskrouter\V1\Workspace\WorkspaceStatisticsList
    {
        return $this->proxy()->statistics;
    }
    /**
     * Magic getter to access properties
     *
     * @param string $name Property to access
     * @return mixed The requested property
     * @throws TwilioException For unknown properties
     */
    public function __get(string $name)
    {
        if (\array_key_exists($name, $this->properties)) {
            return $this->properties[$name];
        }
        if (\property_exists($this, '_' . $name)) {
            $method = 'get' . \ucfirst($name);
            return $this->{$method}();
        }
        throw new \ShopMagicTwilioVendor\Twilio\Exceptions\TwilioException('Unknown property: ' . $name);
    }
    /**
     * Provide a friendly representation
     *
     * @return string Machine friendly representation
     */
    public function __toString() : string
    {
        $context = [];
        foreach ($this->solution as $key => $value) {
            $context[] = "{$key}={$value}";
        }
        return '[Twilio.Taskrouter.V1.WorkspaceInstance ' . \implode(' ', $context) . ']';
    }
}
