<?php

/**
 * This code was generated by
 * \ / _    _  _|   _  _
 * | (_)\/(_)(_|\/| |(/_  v1.0.0
 * /       /
 */
namespace ShopMagicTwilioVendor\Twilio\TwiML;

class VoiceResponse extends \ShopMagicTwilioVendor\Twilio\TwiML\TwiML
{
    /**
     * VoiceResponse constructor.
     */
    public function __construct()
    {
        parent::__construct('Response', null);
    }
    /**
     * Add Connect child.
     *
     * @param array $attributes Optional attributes
     * @return Voice\Connect Child element.
     */
    public function connect($attributes = []) : \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Connect
    {
        return $this->nest(new \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Connect($attributes));
    }
    /**
     * Add Dial child.
     *
     * @param string $number Phone number to dial
     * @param array $attributes Optional attributes
     * @return Voice\Dial Child element.
     */
    public function dial($number = null, $attributes = []) : \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Dial
    {
        return $this->nest(new \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Dial($number, $attributes));
    }
    /**
     * Add Echo child.
     *
     * @return Voice\Echo_ Child element.
     */
    public function echo_() : \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Echo_
    {
        return $this->nest(new \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Echo_());
    }
    /**
     * Add Enqueue child.
     *
     * @param string $name Friendly name
     * @param array $attributes Optional attributes
     * @return Voice\Enqueue Child element.
     */
    public function enqueue($name = null, $attributes = []) : \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Enqueue
    {
        return $this->nest(new \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Enqueue($name, $attributes));
    }
    /**
     * Add Gather child.
     *
     * @param array $attributes Optional attributes
     * @return Voice\Gather Child element.
     */
    public function gather($attributes = []) : \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Gather
    {
        return $this->nest(new \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Gather($attributes));
    }
    /**
     * Add Hangup child.
     *
     * @return Voice\Hangup Child element.
     */
    public function hangup() : \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Hangup
    {
        return $this->nest(new \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Hangup());
    }
    /**
     * Add Leave child.
     *
     * @return Voice\Leave Child element.
     */
    public function leave() : \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Leave
    {
        return $this->nest(new \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Leave());
    }
    /**
     * Add Pause child.
     *
     * @param array $attributes Optional attributes
     * @return Voice\Pause Child element.
     */
    public function pause($attributes = []) : \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Pause
    {
        return $this->nest(new \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Pause($attributes));
    }
    /**
     * Add Play child.
     *
     * @param string $url Media URL
     * @param array $attributes Optional attributes
     * @return Voice\Play Child element.
     */
    public function play($url = null, $attributes = []) : \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Play
    {
        return $this->nest(new \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Play($url, $attributes));
    }
    /**
     * Add Queue child.
     *
     * @param string $name Queue name
     * @param array $attributes Optional attributes
     * @return Voice\Queue Child element.
     */
    public function queue($name, $attributes = []) : \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Queue
    {
        return $this->nest(new \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Queue($name, $attributes));
    }
    /**
     * Add Record child.
     *
     * @param array $attributes Optional attributes
     * @return Voice\Record Child element.
     */
    public function record($attributes = []) : \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Record
    {
        return $this->nest(new \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Record($attributes));
    }
    /**
     * Add Redirect child.
     *
     * @param string $url Redirect URL
     * @param array $attributes Optional attributes
     * @return Voice\Redirect Child element.
     */
    public function redirect($url, $attributes = []) : \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Redirect
    {
        return $this->nest(new \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Redirect($url, $attributes));
    }
    /**
     * Add Reject child.
     *
     * @param array $attributes Optional attributes
     * @return Voice\Reject Child element.
     */
    public function reject($attributes = []) : \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Reject
    {
        return $this->nest(new \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Reject($attributes));
    }
    /**
     * Add Say child.
     *
     * @param string $message Message to say
     * @param array $attributes Optional attributes
     * @return Voice\Say Child element.
     */
    public function say($message, $attributes = []) : \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Say
    {
        return $this->nest(new \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Say($message, $attributes));
    }
    /**
     * Add Sms child.
     *
     * @param string $message Message body
     * @param array $attributes Optional attributes
     * @return Voice\Sms Child element.
     */
    public function sms($message, $attributes = []) : \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Sms
    {
        return $this->nest(new \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Sms($message, $attributes));
    }
    /**
     * Add Pay child.
     *
     * @param array $attributes Optional attributes
     * @return Voice\Pay Child element.
     */
    public function pay($attributes = []) : \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Pay
    {
        return $this->nest(new \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Pay($attributes));
    }
    /**
     * Add Prompt child.
     *
     * @param array $attributes Optional attributes
     * @return Voice\Prompt Child element.
     */
    public function prompt($attributes = []) : \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Prompt
    {
        return $this->nest(new \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Prompt($attributes));
    }
    /**
     * Add Start child.
     *
     * @param array $attributes Optional attributes
     * @return Voice\Start Child element.
     */
    public function start($attributes = []) : \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Start
    {
        return $this->nest(new \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Start($attributes));
    }
    /**
     * Add Stop child.
     *
     * @return Voice\Stop Child element.
     */
    public function stop() : \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Stop
    {
        return $this->nest(new \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Stop());
    }
    /**
     * Add Refer child.
     *
     * @param array $attributes Optional attributes
     * @return Voice\Refer Child element.
     */
    public function refer($attributes = []) : \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Refer
    {
        return $this->nest(new \ShopMagicTwilioVendor\Twilio\TwiML\Voice\Refer($attributes));
    }
}
