<?php

/**
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Bulkexports
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
namespace ShopMagicTwilioVendor\Twilio\Rest\Bulkexports\V1\Export;

use ShopMagicTwilioVendor\Twilio\Exceptions\TwilioException;
use ShopMagicTwilioVendor\Twilio\InstanceResource;
use ShopMagicTwilioVendor\Twilio\Values;
use ShopMagicTwilioVendor\Twilio\Version;
/**
 * @property string|null $friendlyName
 * @property string|null $resourceType
 * @property string|null $startDay
 * @property string|null $endDay
 * @property string|null $webhookUrl
 * @property string|null $webhookMethod
 * @property string|null $email
 * @property string|null $jobSid
 * @property array|null $details
 * @property string|null $jobQueuePosition
 * @property string|null $estimatedCompletionTime
 */
class ExportCustomJobInstance extends \ShopMagicTwilioVendor\Twilio\InstanceResource
{
    /**
     * Initialize the ExportCustomJobInstance
     *
     * @param Version $version Version that contains the resource
     * @param mixed[] $payload The response payload
     * @param string $resourceType The type of communication – Messages or Calls, Conferences, and Participants
     */
    public function __construct(\ShopMagicTwilioVendor\Twilio\Version $version, array $payload, string $resourceType)
    {
        parent::__construct($version);
        // Marshaled Properties
        $this->properties = ['friendlyName' => \ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'friendly_name'), 'resourceType' => \ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'resource_type'), 'startDay' => \ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'start_day'), 'endDay' => \ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'end_day'), 'webhookUrl' => \ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'webhook_url'), 'webhookMethod' => \ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'webhook_method'), 'email' => \ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'email'), 'jobSid' => \ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'job_sid'), 'details' => \ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'details'), 'jobQueuePosition' => \ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'job_queue_position'), 'estimatedCompletionTime' => \ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'estimated_completion_time')];
        $this->solution = ['resourceType' => $resourceType];
    }
    /**
     * Magic getter to access properties
     *
     * @param string $name Property to access
     * @return mixed The requested property
     * @throws TwilioException For unknown properties
     */
    public function __get(string $name)
    {
        if (\array_key_exists($name, $this->properties)) {
            return $this->properties[$name];
        }
        if (\property_exists($this, '_' . $name)) {
            $method = 'get' . \ucfirst($name);
            return $this->{$method}();
        }
        throw new \ShopMagicTwilioVendor\Twilio\Exceptions\TwilioException('Unknown property: ' . $name);
    }
    /**
     * Provide a friendly representation
     *
     * @return string Machine friendly representation
     */
    public function __toString() : string
    {
        return '[Twilio.Bulkexports.V1.ExportCustomJobInstance]';
    }
}
