<?php

/**
 * This code was generated by
 * \ / _    _  _|   _  _
 * | (_)\/(_)(_|\/| |(/_  v1.0.0
 * /       /
 */
namespace ShopMagicTwilioVendor\Twilio\Rest\Api\V2010\Account\Call;

use ShopMagicTwilioVendor\Twilio\Deserialize;
use ShopMagicTwilioVendor\Twilio\Exceptions\TwilioException;
use ShopMagicTwilioVendor\Twilio\InstanceResource;
use ShopMagicTwilioVendor\Twilio\Values;
use ShopMagicTwilioVendor\Twilio\Version;
/**
 * @property string $accountSid
 * @property int $callCount
 * @property int $callFeedbackCount
 * @property \DateTime $dateCreated
 * @property \DateTime $dateUpdated
 * @property \DateTime $endDate
 * @property bool $includeSubaccounts
 * @property string $issues
 * @property string $qualityScoreAverage
 * @property string $qualityScoreMedian
 * @property string $qualityScoreStandardDeviation
 * @property string $sid
 * @property \DateTime $startDate
 * @property string $status
 */
class FeedbackSummaryInstance extends \ShopMagicTwilioVendor\Twilio\InstanceResource
{
    /**
     * Initialize the FeedbackSummaryInstance
     *
     * @param \Twilio\Version $version Version that contains the resource
     * @param mixed[] $payload The response payload
     * @param string $accountSid The SID of the Account that created this resource
     * @param string $sid A string that uniquely identifies this feedback summary
     *                    resource
     * @return \Twilio\Rest\Api\V2010\Account\Call\FeedbackSummaryInstance
     */
    public function __construct(\ShopMagicTwilioVendor\Twilio\Version $version, array $payload, $accountSid, $sid = null)
    {
        parent::__construct($version);
        // Marshaled Properties
        $this->properties = array('accountSid' => \ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'account_sid'), 'callCount' => \ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'call_count'), 'callFeedbackCount' => \ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'call_feedback_count'), 'dateCreated' => \ShopMagicTwilioVendor\Twilio\Deserialize::dateTime(\ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'date_created')), 'dateUpdated' => \ShopMagicTwilioVendor\Twilio\Deserialize::dateTime(\ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'date_updated')), 'endDate' => \ShopMagicTwilioVendor\Twilio\Deserialize::dateTime(\ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'end_date')), 'includeSubaccounts' => \ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'include_subaccounts'), 'issues' => \ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'issues'), 'qualityScoreAverage' => \ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'quality_score_average'), 'qualityScoreMedian' => \ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'quality_score_median'), 'qualityScoreStandardDeviation' => \ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'quality_score_standard_deviation'), 'sid' => \ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'sid'), 'startDate' => \ShopMagicTwilioVendor\Twilio\Deserialize::dateTime(\ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'start_date')), 'status' => \ShopMagicTwilioVendor\Twilio\Values::array_get($payload, 'status'));
        $this->solution = array('accountSid' => $accountSid, 'sid' => $sid ?: $this->properties['sid']);
    }
    /**
     * Generate an instance context for the instance, the context is capable of
     * performing various actions.  All instance actions are proxied to the context
     *
     * @return \Twilio\Rest\Api\V2010\Account\Call\FeedbackSummaryContext Context
     *                                                                    for this
     *                                                                    FeedbackSummaryInstance
     */
    protected function proxy()
    {
        if (!$this->context) {
            $this->context = new \ShopMagicTwilioVendor\Twilio\Rest\Api\V2010\Account\Call\FeedbackSummaryContext($this->version, $this->solution['accountSid'], $this->solution['sid']);
        }
        return $this->context;
    }
    /**
     * Fetch a FeedbackSummaryInstance
     *
     * @return FeedbackSummaryInstance Fetched FeedbackSummaryInstance
     * @throws TwilioException When an HTTP error occurs.
     */
    public function fetch()
    {
        return $this->proxy()->fetch();
    }
    /**
     * Deletes the FeedbackSummaryInstance
     *
     * @return boolean True if delete succeeds, false otherwise
     * @throws TwilioException When an HTTP error occurs.
     */
    public function delete()
    {
        return $this->proxy()->delete();
    }
    /**
     * Magic getter to access properties
     *
     * @param string $name Property to access
     * @return mixed The requested property
     * @throws TwilioException For unknown properties
     */
    public function __get($name)
    {
        if (\array_key_exists($name, $this->properties)) {
            return $this->properties[$name];
        }
        if (\property_exists($this, '_' . $name)) {
            $method = 'get' . \ucfirst($name);
            return $this->{$method}();
        }
        throw new \ShopMagicTwilioVendor\Twilio\Exceptions\TwilioException('Unknown property: ' . $name);
    }
    /**
     * Provide a friendly representation
     *
     * @return string Machine friendly representation
     */
    public function __toString()
    {
        $context = array();
        foreach ($this->solution as $key => $value) {
            $context[] = "{$key}={$value}";
        }
        return '[Twilio.Api.V2010.FeedbackSummaryInstance ' . \implode(' ', $context) . ']';
    }
}
