<?php

/**
 * This code was generated by
 * \ / _    _  _|   _  _
 * | (_)\/(_)(_|\/| |(/_  v1.0.0
 * /       /
 */
namespace ShopMagicTwilioVendor\Twilio\Rest\IpMessaging\V2\Service\User;

use ShopMagicTwilioVendor\Twilio\Options;
use ShopMagicTwilioVendor\Twilio\Values;
abstract class UserBindingOptions
{
    /**
     * @param string $bindingType The push technology used by the User Binding
     *                            resources to read
     * @return ReadUserBindingOptions Options builder
     */
    public static function read($bindingType = \ShopMagicTwilioVendor\Twilio\Values::NONE)
    {
        return new \ShopMagicTwilioVendor\Twilio\Rest\IpMessaging\V2\Service\User\ReadUserBindingOptions($bindingType);
    }
}
class ReadUserBindingOptions extends \ShopMagicTwilioVendor\Twilio\Options
{
    /**
     * @param string $bindingType The push technology used by the User Binding
     *                            resources to read
     */
    public function __construct($bindingType = \ShopMagicTwilioVendor\Twilio\Values::NONE)
    {
        $this->options['bindingType'] = $bindingType;
    }
    /**
     * The push technology used by the User Binding resources to read. Can be: `apn`, `gcm`, or `fcm`.  See [push notification configuration](https://www.twilio.com/docs/chat/push-notification-configuration) for more info.
     *
     * @param string $bindingType The push technology used by the User Binding
     *                            resources to read
     * @return $this Fluent Builder
     */
    public function setBindingType($bindingType)
    {
        $this->options['bindingType'] = $bindingType;
        return $this;
    }
    /**
     * Provide a friendly representation
     *
     * @return string Machine friendly representation
     */
    public function __toString()
    {
        $options = array();
        foreach ($this->options as $key => $value) {
            if ($value != \ShopMagicTwilioVendor\Twilio\Values::NONE) {
                $options[] = "{$key}={$value}";
            }
        }
        return '[Twilio.IpMessaging.V2.ReadUserBindingOptions ' . \implode(' ', $options) . ']';
    }
}
