<?php

/**
 * This code was generated by
 * \ / _    _  _|   _  _
 * | (_)\/(_)(_|\/| |(/_  v1.0.0
 * /       /
 */
namespace ShopMagicTwilioVendor\Twilio\TwiML\Voice;

use ShopMagicTwilioVendor\Twilio\TwiML\TwiML;
class SsmlSub extends \ShopMagicTwilioVendor\Twilio\TwiML\TwiML
{
    /**
     * SsmlSub constructor.
     *
     * @param string $words Words to be substituted
     * @param array $attributes Optional attributes
     */
    public function __construct($words, $attributes = [])
    {
        parent::__construct('sub', $words, $attributes);
    }
    /**
     * Add Alias attribute.
     *
     * @param string $alias Substitute a different word (or pronunciation) for
     *                      selected text such as an acronym or abbreviation
     */
    public function setAlias($alias) : self
    {
        return $this->setAttribute('alias', $alias);
    }
}
